version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/inquery-gateway"
    schedule:
      interval: "monthly"
      time: "02:00"
    open-pull-requests-limit: 20
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "03:00"
