version: '3.8'

services:
  redis:
    image: 'redis:7.2.5'
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped

  database:
    image: mysql:8.0
    container_name: inquerydb
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - inquery-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080

  inquery-app-backend:
    build:
      context: .
      args:
        - NPM_TOKEN=NPM_TOKEN
    environment:
      DATABASE_TYPE: ${DATABASE_TYPE}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      APP_CLIENT_ID: ${APP_CLIENT_ID}
    depends_on:
      - database
      - adminer
      - redis
    ports:
      - 3001:3001

volumes:
  redis_data:
    driver: local
  inquery-data:
