version: "3.7"

services:
  redis:
    image: "redis:7.2.5"
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres:16.2-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  streaming:
    build:
      context: .
    depends_on:
      - postgres
      - adminer
    environment:
      DATABASE_TYPE: ${DATABASE_TYPE}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      APP_CLIENT_ID: ${APP_CLIENT_ID}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - 3003:3003
volumes:
  redis_data:
    driver: local
  postgres-data:
