version: "3.7"

services:
  inquery-app-frontend:
    build:
      context: .
      args:
        - NPM_TOKEN=NPM_TOKEN
    environment:
      API_BASE_URL: ${API_BASE_URL}
    ports:
      - 3000:3000
